version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - C:\studyAndWork\RESTandCRUD\db\postgres\data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - '8082:5432'